name: Ubuntu 20.04 build

on: [push, pull_request]

jobs:

  ubuntu_20_04_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        #run: docker build -f .github/workflows/Dockerfile -t test .
        run: docker run --privileged=true -v $PWD:/build -v /var/run/docker.sock:/var/run/docker.sock ubuntu:18.04 /build/my.sh
